[build]
  builder = "dockerfile"
  buildCommand = "docker build -t tiktok-scraper ."

[deploy]
  startCommand = "node server.js"
  healthcheckPath = "/health"
  healthcheckTimeout = 60
  restartTimeout = 300
  
[build.environment]
  NODE_ENV = "production"
  PORT = "4000"
  IS_RAILWAY = "true"
  RAILWAY = "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_PATH = "/usr/bin/chromium"
  CHROME_BIN = "/usr/bin/chromium"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
  
[build.docker]
  dockerfile = "Dockerfile"
  
[build.docker.buildArgs]
  NODE_ENV = "production"
  
[deploy.healthcheck]
  type = "http"
  path = "/health"
  timeout = 60
  interval = "60s"
  threshold = 3
  initialDelay = "30s"
  
[deploy.resources]
  # Adjust these based on your needs
  cpu = 2
  memory = 2048
  
[deploy.checks]
  enabled = true
  timeout = 60
  interval = "30s"
  retries = 3
