[build]
  builder = "dockerfile"
  buildCommand = "docker build -t tiktok-scraper ."

[deploy]
  startCommand = "node server.js"

[build.environment]
  NODE_ENV = "production"
  IS_RAILWAY = "true"
  RAILWAY = "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_PATH = "/usr/bin/chromium"
  CHROME_BIN = "/usr/bin/chromium"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
  
[build.docker]
  # This ensures the Dockerfile is used for building the application
  dockerfile = "Dockerfile"
  
[build.docker.buildArgs]
  # Add any build args here if needed
  NODE_ENV = "production"
